controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: false
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: [left_wheel_joint]
    right_wheel_names: [right_wheel_joint]
    wheel_separation: 0.45
    wheel_radius: 0.10
    publish_rate: 50.0
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
    velocity_rolling_window_size: 2
    open_loop: false
    pose_covariance_diagonal: [0.01, 0.01, 0.0, 0.0, 0.0, 0.02]
    twist_covariance_diagonal: [0.01, 0.01, 0.0, 0.0, 0.0, 0.02]
